name: My first pipeline

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Build Image
              run: docker build -t   ${{secretS.Docker_USERNAME}}/portfolio-app .
            - name: list images
              run: docker images
           